<?php
/**
 * Copyright © Postpay. All rights reserved.
 * See LICENSE for license details.
 */

/**
 * @var \Postpay\Payment\Block\Widget\Product $block
 */

?>

<<script type="text/x-magento-init">
    {
        "*": {
            "Postpay_Payment/js/view/one": {
                "currency": "<?= $block->escapeHtmlAttr($block->getCurrencyCode()); ?>",
                "merchantid":"<?= $block->escapeHtmlAttr($block->getMerchantId()); ?>",
                "cart" :"<?= $block->escapeHtmlAttr($block->getMaskedCartId()); ?>",
                "cid": "<?= $block->escapeHtmlAttr($block->getUserId()); ?>"
            }
        }
    }
</script>
