<?php
/**
 * Copyright © Postpay. All rights reserved.
 * See LICENSE for license details.
 */

/**
 * @var \Postpay\Payment\Block\Widget\Product $block
 */

$config = [
    'merchantId' => $block->getmerchantId(),
    'sandbox' => $block->isSandbox()
];
?>

<div data-mage-init='{"postpayWidget": <?= $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($config) ?>}'>
    <div
        class="postpay-widget"
        data-type="product"
        data-amount="<?php echo $block->getFinalPrice()->jsonSerialize(); ?>",
        data-currency="<?php echo $block->getCurrencyCode(); ?>"
    ></div>
</div>
