<?php
/**
 * Copyright © Postpay. All rights reserved.
 * See LICENSE for license details.
 */

/**
 * @var \Postpay\Payment\Block\Widget\Product $block
 */

use Magento\Framework\Json\Helper\Data;

$config = [
    'merchantId' => $block->getmerchantId(),
    'sandbox' => $block->isSandbox()
];
?>

<div data-mage-init='{"postpayWidget": <?= $this->helper(Data::class)->jsonEncode($config) ?>}'>
    <div
        class="postpay-widget"
        data-type="product"
        data-amount="<?= echo $block->escapeHtmlAttr($block->getFinalPrice()->jsonSerialize()); ?>",
        data-currency="<?= echo $block->escapeHtmlAttr($block->getCurrencyCode()); ?>"
    ></div>
</div>
